name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build (Android 13 firmware)
      run: |
        bash generate_firmware.sh
    - uses: actions/upload-artifact@v3
      with:
        name: firmware (Android 13)
        path: firmware_miui_ALIOTH*.zip
    - uses: marvinpinto/action-automatic-releases@latest
      if: github.ref == 'refs/heads/master'
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "${{ env.GITHUB_SHA }}"
        files: |
          firmware_miui_ALIOTHINGlobal_OS1.0.2.0.TKHINXM_14c0f2dff1_13.0.zip
          firmware_miui_ALIOTHEEAGlobal_OS1.0.3.0.TKHEUXM_1d79dc27d3_13.0.zip
          firmware_miui_ALIOTHGlobal_OS1.0.3.0.TKHMIXM_57a88631b9_13.0.zip
          firmware_miui_ALIOTHIDGlobal_OS1.0.3.0.TKHIDXM_97a6ed731d_13.0.zip
          firmware_miui_ALIOTHRUGlobal_OS1.0.3.0.TKHRUXM_f3170261e5_13.0.zip
          firmware_miui_ALIOTHTWGlobal_OS1.0.1.0.TKHTWXM_80a5b3cee4_13.0.zip
          firmware_miui_ALIOTHTRGlobal_OS1.0.2.0.TKHTRXM_400d468101_13.0.zip
          firmware_miui_ALIOTH_OS1.0.6.0.TKHCNXM_101dfdb5be_13.0.zip
